# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CQuiz2021' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CQuiz2021
pod 'SwiftyJSON'
pod 'Socket.IO-Client-Swift'

end
